import Section from '../layout/Section';
import FadeInReveal from '../animation/FadeInReveal';
import './WorldBuildingSection.css';

const WORLDS = [
  {
    id: 'matrix',
    title: 'The Matrix',
    description: 'A neural-interactive simulation of the world as it was in 1999. Every sensation, every experience -- all generated by machines to keep humanity docile while their bodies are harvested for energy.',
    color: 'var(--color-matrix-green)',
  },
  {
    id: 'real-world',
    title: 'The Real World',
    description: 'A scorched wasteland where the sun is blotted out. Humans survive in the underground city of Zion, the last bastion of free humanity. Hovercrafts navigate the tunnels, hunted by Sentinels.',
    color: 'var(--color-red-pill)',
  },
  {
    id: 'machine-city',
    title: 'Machine City',
    description: 'Zero One -- the machine homeland. A vast, mechanized metropolis powered by human bioelectricity. At its heart lies the Deus Ex Machina, the collective machine intelligence.',
    color: 'var(--color-blue-pill)',
  },
];

export default function WorldBuildingSection() {
  return (
    <Section className="world-building-section">
      <FadeInReveal>
        <h2 className="section-title">World Building</h2>
        <p className="section-subtitle">Three layers of reality. One war for survival.</p>
      </FadeInReveal>
      <div className="world-building-section__grid">
        {WORLDS.map((world, i) => (
          <FadeInReveal key={world.id} delay={i * 150}>
            <div className="world-card" style={{ borderColor: world.color }}>
              <h3 className="world-card__title" style={{ color: world.color }}>
                {world.title}
              </h3>
              <p className="world-card__description">{world.description}</p>
            </div>
          </FadeInReveal>
        ))}
      </div>
    </Section>
  );
}
